### ISSUE TITLE
PatchFeatureDataset

### ISSUE THREAD

**Issue by Mairafatoretto** [histocartography/zoommil#4]
Hello Kevin, I am having a problem with this function. 
The error is TypeError: BaseDataset.__init__() got an unexpected keyword argument 'split'. 
Even though in the dataset.py there is:

class BaseDataset(Dataset):
    def __init__(self, csv_path, split, label_dict, label_col='type', ignore=[]):

Could you help me?

**Comment by kevthan** [comment]
Hi, could you please provide the full error and which command/script you are running?

**Comment by kevthan** [comment]
Does this problem still occur? If not, we can close this issue
