### ISSUE TITLE
Training with 2-magnification level

### ISSUE THREAD

**Issue by jingweitan** [histocartography/zoommil#8]
Hi, I am trying to implement your method on my dataset. I am wondering that if I want to train with 2 magnification levels only, how can I train the zoommil model? For example, in the sample_config.json, do I have to make the "mid_mag" as empty? and do i need to modify the provided zoommil.py to 2 magnification levels? 

Thanks in advance!

**Comment by kevthan** [comment]
Hi, thanks for your interest in our method!

For 2 magnification levels, you have to modify the code in the following places:
- remove parts with mid_mag in `dataset.py`: (and in `train.py` where `PatchFeatureDataset` is instantiated)
- In `zoommil.py`:
   - remove blocks related to mid_mag
   - in `forward()`: you only need x1 & x3; skip the middle magnification part and connect the low magnification output directly to the high magnification part

With these changes, the mid_mag entries in the config should automatically be ignored.

**Comment by jingweitan** [comment]
Thanks for your quick reply. I am confused with this 2 parts in **zoommil.py**.Which number should I change for the _num_features_ index if I want to use only 2 magnification levels. Supposed that I should change them to 1 and 0 right? Did these 2 parts are the same thing?  

![image](https://github.com/histocartography/zoommil/assets/48575204/14e92c93-aeb9-4081-9cc8-b8f914f8af03)
![image](https://github.com/histocartography/zoommil/assets/48575204/a37c49a8-02e6-4848-a06d-75206721c93e)

**Comment by kevthan** [comment]
For 2 magnification levels it should be:

```
x3 = torch.einsum('bkn,bnd->bkd',
                torch.kron(select_1, torch.eye(int(num_features[1] // num_features[0]), device=self.device, requires_grad=True)), 
                x3)
```

**Comment by jingweitan** [comment]
Alright!! Thanks for your help!
